version: '3.8'
services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=librasdb'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: 'elasticsearch:7.16.3'
    environment:
      - 'discovery.type=single-node'
    ports:
      - "9200:9200"

volumes:
  postgres-data:
