version: '3.8'
services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=librasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - libras-network

  app:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/admin
      SPRING_DATASOURCE_USERNAME: librasdb
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - libras-network

volumes:
  postgres-data:

networks:
  libras-network:
